### ISSUE TITLE
v0.8.1 Exec format error

### ISSUE THREAD

**Issue by whatever4711** [hypriot/rpi-dockerui#4]
The new compiled version is corrupt. 
It shows when running on docker:  **[8] System error: exec format error**

Please update the github link on dockerhub ;)

**Comment by Duvel** [comment]
+1

**Comment by firecyberice** [comment]
Thank you for reporting. I fixed the github link at the dockerhub.
It seems like the CI cross compiled a x86_64 binary.
I just started a new build.

**Comment by Duvel** [comment]
Hi, docker hub says there is a new image, but this still gives the same error. Am I too fast?

Thanks!

**Comment by firecyberice** [comment]
I added a badge to our builder where you can see the build status.
Yes it seems like I have to change something in the build recipe.

**Comment by firecyberice** [comment]
I added a badge to our builder where you can see the build status.
Yes it seems like I have to change something in the build recipe.

**Comment by firecyberice** [comment]
Now is it working. I have tested it on a Scaleway ARM server
